### PR TITLE
Header section skeleton for product landing page

### PR DESCRIPTION
**Pull request by Snooperton**
added some structure to the header of the product landing page

### CODE REVIEW

**Comment by Snooperton** [comment]
just creating some skeletal stuff atm, will be trying to incorporate classes in thier own <div> elements later in order to make the CSS stuff easier. lemme know what u think so far

**Comment by Snooperton** [comment]
added some Nav bar skeletal stuff

**Comment by Snooperton** [comment]
added dead links to the nav bar

**Review by nicholasmueller — APPROVED** [review]
No need to comment on the pr after every commit btw, the commit message should speak for itself

**Comment by Snooperton** [comment]
cool thanks, will do

**Pull request merged**
